# Generated by Django 4.1.6 on 2024-02-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_options_alter_difficulty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
